### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by kyloknight** [bliles/wp-admin10x#3]
How would all your code look as a function for the functions.php file? I tried copy pasting it all in a functions file and it works like a gem with performance, but when editing posts no author is returned, its just blank. 

I cant activate the plugin as it returns the titled error, I have tried disabling every other plugin, still not luck. 54k users with role "customer" causing the slow admin issue on my clients site, what can I do :(?

**Comment by bliles** [comment]
Sorry I somehow missed your issue. I'll see if I can duplicate your error and provide a fix.

**Comment by bliles** [comment]
I just tested on WP 5 and the plugin installed correctly and the author dropdown was properly populated. What version of WP are you using?

**Comment by bliles** [comment]
Please reopen issue if needed.
